### ISSUE TITLE
[bug] react-select-search integrated in a next.js app

### ISSUE THREAD

**Issue by handrei** [tbleckert/react-select-search#99]
hello, right now i'm moving an create-react-app into a next.js app and i have the following issue:
SyntaxError: Unexpected token export

/path-to-app/node_modules/react-select-search/dist/esm/index.js:1
export { default as useSelect } from './useSelect';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack-internal:///react-select-search:1:18)
    at Object.react-select-search (/path-to-app/.next/server/static/development/pages/profile.js:480:1)
    at __webpack_require__ (/path-to-app/.next/server/static/development/pages/profile.js:23:31)
    at eval (webpack-internal:///./pages/profile/index.js:6:77)
    at Module../pages/profile/index.js (/path-to-app/.next/server/static/development/pages/profile.js:303:1)
    at __webpack_require__ (/path-to-app/.next/server/static/development/pages/profile.js:23:31)
    at Object.4 (/path-to-app/.next/server/static/development/pages/profile.js:336:18)
    at __webpack_require__ (//path-to-app/.next/server/static/development/pages/profile.js:23:31)
    at //path-to-app/.next/server/static/development/pages/profile.js:91:18

any help would be nice :D

**Comment by handrei** [comment]
i resolved the issue by accessing the module with:
 - import SelectSearch from 'react-select-search/dist/cjs';

**Comment by jibin2706** [comment]
@handrei getting the following type error
```
Could not find a declaration file for module 'react-select-search/dist/cjs'. '.../node_modules/react-select-search/dist/cjs/index.js' implicitly has an 'any' type.
```
